### PR TITLE
Add Mermaid Diagrams to Supervisor strategies

### PR DESCRIPTION
**Pull request by AdrianPaulCarrieres**
image

#288

### CODE REVIEW

**Comment by AdrianPaulCarrieres** [comment]
I didn't find how to add the little arrows from Erlang's documentation with the restart and termination order:

image

**Comment by AdrianPaulCarrieres** [comment]
Sorry, I just saw that you mentioned another issue with the Mermaid one.


I will take a look too!

**Comment by AdrianPaulCarrieres** [comment]
I just thought about that but I guess it would be better to move the diagram later in the Livebook, each one with the strategy example with the bomb?

**Comment by BrooklinJazz** [comment]
This is awesome! I think this is an improvement so I'd love to merge it in.

There's a failing test though, you can run `mix format_headings`, and I think it should resolve the issue.

In a future PR We could use `Kino.Process` to visualize the supervisor tree with the bombs but that's something I'll take a look at when I have some time. For now I think this is an excellent addition. Thank you!

**Comment by AdrianPaulCarrieres** [comment]
Thanks! <3

**Comment by BrooklinJazz** [comment]
🚀🚀🚀

**Pull request merged**
