### PR TITLE
tiny typo fix

### PR DESCRIPTION
**Pull request by threetriangles**

### CODE REVIEW

**Comment by BrooklinJazz** [comment]
Why did you close this? It looks good to me

**Comment by threetriangles** [comment]
I found more problems but I didn’t have time to fix them all. Some of the links to Faker don’t work.

**Comment by BrooklinJazz** [comment]
Hmm, would you mind raising an issue to capture this? We can always circle back to them or make them good beginner-friendly tickets.

**Comment by threetriangles** [comment]
Sure I’ll do that.

**Pull request closed without merging**
