### PR TITLE
Update nix files

### PR DESCRIPTION
**Pull request by mvkvc**
Update nix files to use specific erlang and elixir versions and install livebook on first shell automatically.

### CODE REVIEW

**Comment by mvkvc** [comment]
Going to check if it works on Mac/Windows

**Comment by BrooklinJazz** [comment]
Hey @mvkvc can you help me understand the purpose of this PR?

I don't use nix personally. I accepted adding these files originally since it was requested by nix users.

Is using specific versions rather than generic versions an improvement? I'm concerned about adding overhead to managing these files. Does this solve some issues I'm not aware of?

**Comment by mvkvc** [comment]
Nix uses a rolling release so the current version of the `elixir` package is 1.13, and because livebook updates require using the latest version of elixir when installing, the old version of `nix.flake` does not work anymore. I tried it now and got the error `** (Mix) You're trying to run :livebook on Elixir v1.13.4 but it has declared in its mix.exs file it supports only Elixir ~> 1.14.2`.

As long as livebook keeps requiring the latest elixir version and the version of livebook and elixir is not pinned in the course then it is necessary to occasionally bump the version number like similar tools such as asdf. I can maintain this for the forseeable future as I am using it for the course, and maybe also add a note in the file that this is a DIY method without support.

**Comment by BrooklinJazz** [comment]
I'm wondering if we should remove nix from the project 🤔 It's easy for these kinds of configs to get out of date, and I only plan to monitor asdf for breaking changes.

Thoughts?

**Comment by mvkvc** [comment]
Makes sense if it's not something that you want to deal with. I'll close this PR and then keep the files in my fork.

**Pull request closed without merging**
