### PR TITLE
Corrected typo in test case

### PR DESCRIPTION
**Pull request by SRFowler**
In "Filter Values By Type"

### CODE REVIEW

**Comment by SRFowler** [comment]
Corrections are incomplete

**Comment by BrooklinJazz** [comment]
It looks like you committed some of your completed exercise. Can you remove the solution so only the typo is part of the PR?

**Comment by BrooklinJazz** [comment]
> Corrections are incomplete

Handy Tip: It's common to put [WIP] in the title of the PR if you are still in progress. Also, I believe there's a draft feature on GitHub but I have not personally used it.

**Comment by SRFowler** [comment]
Okay, I think I have it fixed. If there's a better way than Revert I have not found it.
I had livebook open when switching branches so I think some data got moved that I did not intend.

**Comment by BrooklinJazz** [comment]
Closes #448

**Comment by BrooklinJazz** [comment]
Great work thank you!

**Pull request merged**
