### PR TITLE
Auto insert navigation at bottom of page

### PR DESCRIPTION
**Pull request by mvkvc**
WIP

- [X] Parse readings in order from start.md
- [X] Figure out html tags for left and right align text inline
- [ ] Check for existing navigation at bottom of page and replace/delete
- [ ] Add new navigation information

### CODE REVIEW

**Comment by BrooklinJazz** [comment]
As a heads up, we'll want to ensure this does not conflict with the script to add the commit sections. Thank you so much for working on this!

**Comment by mvkvc** [comment]
Yes for sure. Just to be clear this should be at the bottom after the git section right? And should I also make it a mix task?

**Comment by BrooklinJazz** [comment]
> Yes for sure. Just to be clear this should be at the bottom after the git section right? And should I also make it a mix task?

Hi @mvkvc! I'm sorry I thought I had responded to this but I did not!

Yes, it should be at the bottom after the git section. Making it a mix task would be fantastic.

**Comment by BrooklinJazz** [comment]
@mvkvc How is this going? I'm doing a content review tomorrow, and it would be awesome to have this feature.
If you don't mind, I might grab what you've done and see if I can finish it for tmr

**Comment by BrooklinJazz** [comment]
Draft solution in #281 . I would be happy to get your thoughts! Apologies if I'm stepping on your toes by implementing this.

I couldn't get anchor tags working with relative links, so I used markdown links inside a table. I'd like to improve the UI but this is "good enough" for my purposes tomorrow to get feedback.

**Comment by mvkvc** [comment]
@BrooklinJazz sorry I didn't see you tagged me and I have just been so busy recently and meant to get to it this weekend. Happy to see that you got it working and I will check out your solution :+1:.

**Pull request closed without merging**
