### PR TITLE
Boolean Operators exercise: Replace Utils.feedback with TestedCell

### PR DESCRIPTION
**Pull request by Mraiih**
Still in order to help (and learn Elixir), I saw this issue https://github.com/DockYard-Academy/beta_curriculum/issues/170 and think I can help with it.

I tried with `TestedCell`, maybe I should use `ExerciseCell` instead?

### CODE REVIEW

**Comment by BrooklinJazz** [comment]
This is awesome! How was working with `TestedCell`? Are there any improvements you would suggest? It's pretty new.

I'm torn between `TestedCell` and `Exercise`. `TestedCell` is super convenient and fast. However, it's easier to make mistakes where the hint and the assertions don't match. `Exercise` is nicely validated, however, it makes a new smart cell for every test, so it will result in bloated code.

Maybe the best of both worlds is to write a test that reads all files in the academy, finds `TestedCell` blocks, then evaluates the contents of the hint and the assertion to ensure there are no issues.

I'm going to merge any PRs with either `Exericise` or `TestedCell`. I think we should prefer `TestedCell` for now though.

**Comment by Mraiih** [comment]
> How was working with TestedCell?

Difficult to say, I don't think I was using it right. In the screen you shared on the issue ( https://user-images.githubusercontent.com/14877564/181367656-2238940e-8bbe-404d-acc5-5076c3ea22c3.png ), you seem to have an input for assertions that I don't have.

I still did it by creating an empty `TestedCell` on Livebook, adding the bing of the variable there (that autocomplete the `code` attribute on `attrs` hash), then in VSCode adding the assertions, in the `Assertion` module and in the `assertion` attribute of the `attrs` hash.

I don't feel it's the correct way to do but still managed to make this PR.

On the other side, it seems that I could make both changes in the `TestedCell` when I use the `toggle source` button but the editor is on read-only (for people to don't mess with specs?)

----

I didn't use `ExerciseCell` yet, but from what I understand, you keep the hint (possible solution), and assertions (feedback) in the `Util.SmartCell.Exercise.xxxx` module then you just have to add
```
<!-- livebook:{"attrs":{},"kind":"Elixir.Utils.SmartCell.Exercise.xxxx","livebook_object":"smart_cell"} -->
```
I really like the use of the strategy pattern for this, making it easily readable and open to extension

**Comment by BrooklinJazz** [comment]
Ah! see #176 for instructions on how to turn on the editor flag. the editor is hidden for students, but we can enable it to write the tests.

**Comment by BrooklinJazz** [comment]
I also really like the code for `ExerciseCell`. But the behavior is problematic. Eventually, the dropdown input for smart cells would have literally hundreds of options. 😭

**Comment by BrooklinJazz** [comment]
Oh shoot, I just realized these don't have hints, which causes rendering issues.

image

I should have tested properly! I'll make a quick fix.

**Comment by Mraiih** [comment]
> Ah! see #176 for instructions on how to turn on the editor flag. the editor is hidden for students, but we can enable it to write the tests.

Thanks! I'll check that 😄 

> Eventually, the dropdown input for smart cells would have literally hundreds of options.

Are options something global to Livebook or can we have different options depending which page we are currently?

> Oh shoot, I just realized this file doesn't import makeup and makeup elixir which causes rendering issues.

Most of page I gone through don't have them, I can make a PR to add them!

> We also need to add hints.

oops, my bad, I thought that was optional

**Pull request merged**
