### PR TITLE
Fix issue #472

### LINKED ISSUE #472: Add Pull Request to Git Instructions
image

Students should start an exercise by ensuring they are on the `main` branch, then they should create a new branch for the exercise.

At the top of every lesson we should include instructions like so:

### Create an Exercise Branch
`git checkout -b exercise-name`

Then include PR instructions
`git add .`
`git commit -m "complete exercise-name"`
`git push -u origin exercise-name`
Then create a pull request. @mention your teacher to get their review.
Review the files changed to ensure they are correct.

### PR DESCRIPTION
**Pull request by pascalwengerter**
Fixes #472, needs a rebase once #473 is merged

### CODE REVIEW

**Comment by BrooklinJazz** [comment]
I've merged in #473

**Comment by BrooklinJazz** [comment]
I think we should also add these git commit sections to Readings now that I think about this 🤔

**Comment by BrooklinJazz** [comment]
I've resolved the conflicts and slightly modified the script in #550, your commits will exist in that PR. Thank you so much for this contribution @pascalwengerter!

**Comment by pascalwengerter** [comment]
> I've resolved the conflicts and slightly modified the script in #550, your commits will exist in that PR. Thank you so much for this contribution @pascalwengerter!

Ah nice thanks @BrooklinJazz, forgot about picking this one back up (and had some issues about it creating empty files IIRC 😅 ). Glad to have contributed, though!

**Pull request closed without merging**
